train_file: '/workspace/Harm_C/ALBEF/train.json'
val_seen_file: '/workspace/Harm_C/ALBEF/val.json'                
test_seen_file: '/workspace/Harm_C/ALBEF/test.json'

image_root: '/workspace/Harm_C/images'



image_res: 224
batch_size_train: 16
batch_size_test: 128

alpha: 0.4
distill: False
warm_up: False

bert_config: '/workspace/project/ALBEF/configs/config_bert.json'
config: '/workspace/project/ALBEF/configs/config.json'

optimizer: {opt: adamW, lr: 2e-7, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-7, epochs: 20, min_lr: 1e-8, decay_rate: 1, warmup_lr: 1e-7, warmup_epochs: 1, cooldown_epochs: 0}










