train_file: '/home/ycp/HM/Harm/Data/FHM/ALBEF/train.json'
val_seen_file: '/home/ycp/HM/Harm/Data/FHM/ALBEF/dev_seen.json'                
val_unseen_file: '/home/ycp/HM/Harm/Data/FHM/ALBEF/dev_unseen.json'                
test_seen_file: '/home/ycp/HM/Harm/Data/FHM/ALBEF/test_seen.json'
test_unseen_file: '/home/ycp/HM/Harm/Data/FHM/ALBEF/test_unseen.json'

image_root: '/home/ycp/HM/Harm/Data/FHM/img'


image_res: 224
batch_size_train: 16
batch_size_test: 128 

alpha: 0.4
distill: False
warm_up: False

bert_config: '/home/ycp/HM/configs/config_bert.json'
config: '/home/ycp/HM/configs/config.json'


optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 20, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-4, warmup_epochs: 1, cooldown_epochs: 0}










