train_file_t: '/workspace/twitter/ALBEF/train.json'
val_file_t: '/workspace/twitter/ALBEF/val.json'                
test_file_t: '/workspace/twitter/ALBEF/test.json'

image_root_t: '/workspace/twitter/img/dataset_image'

image_res: 224
batch_size_train: 16
batch_size_test: 128 

alpha: 0.4
distill: False
warm_up: False

bert_config: '/workspace/project/ALBEF/configs/config_bert.json'
config: '/workspace/project/ALBEF/configs/config.json'

optimizer: {opt: adamW, lr: 1e-3, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-3, epochs: 20, min_lr: 1e-4, decay_rate: 1, warmup_lr: 1e-2, warmup_epochs: 1, cooldown_epochs: 0}







